name: Test suite
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "branch on which to run tests: master"
        required: true
        type: string
        default: master
      test-tags:
        description: "test tags, in the form of a list without spaces: 'all,dns' "
        required: false
        type: string
        default: all
      tf-log:
        description: "terraform logs, accepted values: off, trace, debug, info, warn or error"
        required: false
        type: string
        default: off
jobs:
  test:
    env:
      TEST_DNS_ZONE_NAME: test-dns-go-sdk.com
      IONOS_API_KEY: ${{ secrets.X_API_KEY }}
      TF_ACC: true
      TF_LOG: ${{ github.event.inputs.tf-log }}
    strategy:
      matrix:
        go-version: [^1.17]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Run tests with tags
        if: ${{ github.event.inputs.test-tags != '' }}
        run: go test ./ionosdeveloper -v -failfast -timeout 10m -tags ${{ github.event.inputs.test-tags }}
      - name: Run tests without tags
        if: ${{ github.event.inputs.test-tags == ''}}
        run: go test ./ionosdeveloper -v -failfast -timeout 10m
